---
- hosts: network
  become: yes
  tasks:
    - name: copy interfaces
      copy: src=config/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: copy FRR daemons
      copy: src=config/{{ansible_hostname}}/daemons dest=/etc/frr/
    - name: copy FRR conf
      copy: src=config/{{ansible_hostname}}/frr.conf dest=/etc/frr/
    - name: reload networking
      command: ifreload -a
    - name: reload frr
      service: name=frr state=restarted

- hosts: servers
#  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - install-ifupdown2
  tasks:
    - name: copy interfaces
      copy: src=config/{{ansible_hostname}}/interfaces dest=/etc/network/      
    - name: restarts networking with their new configuration
      command: ifreload -a
